# Dockerfile

# base image
FROM node:16-alpine

# create & set working directory
RUN mkdir -p /usr/src/frontend
WORKDIR /usr/src/frontend

# copy source files
COPY ./frontend /usr/src/frontend

# install dependencies
RUN npm install
RUN npm install -g @angular/cli

# start app
RUN npm run build
EXPOSE 4200
CMD ["ng", "serve", "--host=0.0.0.0"]