# Dockerfile

# base image
FROM node:16-alpine

# create & set working directory
RUN mkdir -p /usr/src/backend
WORKDIR /usr/src/backend

# copy source files
COPY ./backend /usr/src/backend

# install dependencies
RUN npm install

# start app
RUN npm run build
EXPOSE 3000
CMD npm run start